app:
  debug: true

model:
  nas_rental_prediction:
    path: models/nas_rental_prediction/best_model_new_saved
  shaqirah_mushroom:
    path: models/shaqirah_mushroom/feature_engineering_model


server:
  host: "0.0.0.0"
  port: 5000

logging:
  level: "INFO"
